# ArgoCD Application — watches Helm chart in Git, auto-syncs to EKS
# VPC: vpc-016ee8add8c12b1cf (shopzone-vpc)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopzone
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/balatsr0306-rgb/shopzone-ecommerce.git   # ← change
    targetRevision: main
    path: helm/shopzone
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: global.imageRegistry
          value: "187352848533.dkr.ecr.ap-south-1.amazonaws.com"   # ← change ACCOUNT_ID

  destination:
    server: https://kubernetes.default.svc
    namespace: shopzone

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
