apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopzone-frontend
  labels:
    app: shopzone-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: shopzone-frontend
  template:
    metadata:
      labels:
        app: shopzone-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: shopzone-frontend
spec:
  selector:
    app: shopzone-frontend
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
