apiVersion: v1
kind: Pod
metadata:
  name: migration-debug
  namespace: shopzone
spec:
  restartPolicy: Never
  containers:
  - name: migrate
    image: 187352848533.dkr.ecr.ap-south-1.amazonaws.com/shopzone-backend:v1.1
    command:
      - node
      - src/config/migrate.js
    env:
    - name: NODE_ENV
      value: "production"

    - name: DB_HOST
      value: "shopzone.cx2gwesm047r.ap-south-1.rds.amazonaws.com"

    - name: DB_PORT
      value: "5432"

    - name: DB_NAME
      value: "ecommerce"

    - name: DB_USER
      value: "postgres"

    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: shopzone-db-secret
          key: DB_PASSWORD
